# Generated by Django 5.2.5 on 2025-09-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
